### ISSUE TITLE
Network broken when downloading SCEDC dataset!!!

### ISSUE THREAD

**Issue by FoolHuangECNU** [seisbench/seisbench#115] opened 2022-07-22 00:21 UTC
Hello, I have been downloading SCEDC dataset for several days.
When it is almost done, the network was broken!!!
I have downloaded 400+ GB of 662GB totally in SCEDC dataset. 
How can I do to download the data continuely? I really don't want to wait for another several days. T.T

**Comment by yetinam** [comment] 2022-07-25 07:54
Hi @FoolHuangECNU ,

sorry to hear your download broke. SeisBench itself unforunately can not continue broken downloads. However, you can try doing this manually through the command line, for example [using wget](https://www.cyberciti.biz/tips/wget-resume-broken-download.html). The URL of the SCEDC dataset is https://dcache-demo.desy.de:2443/Helmholtz/HelmholtzAI/SeisBench/datasets/scedc/waveforms.hdf5.

As a sidenote, to avoid this issue in the future, we might want to chunk the SCEDC dataset into smaller pieces. What do you think, @jawooll ?

**Comment by yetinam** [comment] 2022-08-04 16:28
Closing this for now, feel free to reopen if the issue is not yet solved.

**Closed by yetinam** 2022-08-04 16:28 UTC
Labels: question
