### ISSUE TITLE
STEAD Data set

### ISSUE THREAD

**Issue by Grexilo** [seisbench/seisbench#128] opened 2022-09-28 20:12 UTC
I read in the Seisbench documentation that we can use the STEAD data set.

I have download the data set in my local machine, but according to the documentation fro creating the class we don't need to use any argument to created, so for my is not clear ow to use this data set.

Someone can help me with this?

**Comment by Grexilo** [comment] 2022-09-29 13:57
Hi @yetinam 

Thank you for taking your time and replay to my issue.

I I tried the command but I got this error message when I run that. I really interested in using the STEAD data set for training the PhaseNet.

![image](https://user-images.githubusercontent.com/43388194/193050511-383f7f81-933d-4fd8-bfbb-6c9fafb8b262.png)
![image](https://user-images.githubusercontent.com/43388194/193050570-58ef93f8-9a0b-4d0d-8ff7-fe958c3beebf.png)

**Comment by yetinam** [comment] 2022-09-29 14:04
Hey @Grexilo,

that's curious. Which files do you have in the folder "D:/STEAD"? There should be one file `merged.csv` and one file `merged.hdf5`. Do you maybe still have the separate chunks? In that case, you'll need to merge them first.

**Comment by Grexilo** [comment] 2022-09-29 14:40
Hey @yetinam 

I found a typo in the files, and I think it's working now. 
I will to train the PhaseNet model with that data set. Also I created a new data set for the same purpose, training the PhaseNet model.
If I encounter any problems using STEAD and my data set, could I contact you?

**Comment by yetinam** [comment] 2022-09-29 14:53
Great to hear the issue is resolved! Sure, feel free to open another issue if you encounter further problems.

Two more short remarks:

- There is actually also a version of PhaseNet trained on STEAD available directly through SeisBench. You can load it with `sbm.PhaseNet.from_pretrained("stead")`.
- For an example of a more comprehensive training script than the one in our tutorial notebook, you might want to have a look at our [benchmark code](https://github.com/seisbench/pick-benchmark). In particular, you might be interested in the [set of augmentations used](https://github.com/seisbench/pick-benchmark/blob/2fae5941f632fb2146e6bea37f94eb89a2c89bc7/benchmark/models.py#L159).

**Closed by yetinam** 2022-09-29 14:53 UTC
Labels: question

**Comment by Grexilo** [comment] 2022-09-29 15:00
Sure!
I want to trained by my own and see how this works. I want to learn how to present my new data to the network using SeisBench.

According with the documentation of SeisBench I think I need to use the class [WaveFormDataWriter](https://seisbench.readthedocs.io/en/stable/pages/documentation/data.html#seisbench.data.base.WaveformDataWriter). So I will try to used and I will let you know if it works or not. 

Thank you for your time @yetinam

**Comment by yetinam** [comment] 2022-09-30 10:38
STEAD is now available directly from our repositories as of 02531f771679ee377aea070f9899b23907732f6e, i.e., SeisBench 0.2.6.
