### ISSUE TITLE
Why the responses of the same model differ in different model parameter loading styles?

### ISSUE THREAD

**Issue by JUNZHU-SEIS** [seisbench/seisbench#79] opened 2022-04-07 12:37 UTC
Below I test two approaches to load the parameters:
```
# 1. the first use the seisbench model
tl_stead = sbm.PhaseNet(phases='PSN').to(device)
tl_stead.load_state_dict(torch.load('models/direct_tl/stead.pt',
			map_location=device).state_dict())
# 2. the second use the torch.load function
tl_stead = torch.load('models/direct_tl/stead.pt').to(device)
```
The responses of a common input differ in these two loading styles.
Anybody can answer this question?

**Comment by yetinam** [comment] 2022-04-07 16:15
Hey @JUNZHU-SEIS ,
thanks for reaching out. To help with your question, could you provide us with further information?

- What exactly is the file `stead.pt`? Is this the file provided through `from_pretrained` or did you create it? In the later case, could you provide us with the file to help debugging the issue?
- What do you mean with different responses? Do you provide the same input tensor to the model and get different outputs? How big are the differences?

**Comment by JUNZHU-SEIS** [comment] 2022-04-08 01:23
Thanks a lot for your reply.
* I create the file [stead.zip](https://github.com/seisbench/seisbench/files/8447706/stead.zip) by transfer learning in GPU.
* The responses are the outputs of the model. I feed the model with the same input tensor but get different outputs. Sometimes the differences are minor, sometimes are big enough to result in different picks. See the differences below:
![Figure_1](https://user-images.githubusercontent.com/73752214/162344546-cb96092b-29bb-46a4-b8e4-2fce7be08ac6.png)
![Figure_2](https://user-images.githubusercontent.com/73752214/162344554-038d977c-7de4-4fcd-a4ed-62de98973f21.png)

**Comment by JUNZHU-SEIS** [comment] 2022-04-08 07:27
With the help of [Yiyu](https://www.bing.com/search?form=MOZLBR&pc=MOZI&q=yiyu+ni) I found the reason. Because I did not apply the ```model.eval()``` method before prediction. If I apply this method, however, the outputs are more variable, i.e., losing some smoothness.

**Comment by yetinam** [comment] 2022-04-08 07:28
Great that the issue is solve. Closing this now. Feel free to reach out again if you have further questions!

**Closed by yetinam** 2022-04-08 07:28 UTC
Labels: question

**Comment by yetinam** [comment] 2022-04-08 09:13
Just a short addition, given that you mentioned you are working on transfer learning. You could also try using the models available through SeisBench using `from_pretrained` as a basis for your transfer learning.

**Comment by JUNZHU-SEIS** [comment] 2022-04-12 01:49
> Just a short addition, given that you mentioned you are working on transfer learning. You could also try using the models available through SeisBench using `from_pretrained` as a basis for your transfer learning.

Thanks for your recommendations. We do have used the ```from_pretrained``` as a basis for transfer learning. Our results suggest that the *STEAD* model outperforms *SCEDC* model.

**Comment by zhong-yy** [comment] 2023-03-30 04:13
Hi @JUNZHU-SEIS , could you have a look at this [issue](https://github.com/seisbench/seisbench/issues/186) ,the performance becomes worse after I apply model.eval()
