### ISSUE TITLE
Unable to access data

### ISSUE THREAD

**Issue by Dong6Jx** [seisbench/seisbench#207] opened 2023-06-12 12:53 UTC
I want to access your datasets. I am running your example: 01a_dataset_basics and I am getting this error on line "data = sbd.DummyDataset()"

Traceback (most recent call last):
  File "D:\anaconda3\envs\SeisBench\lib\site-packages\urllib3\connection.py", line 200, in _new_conn
    sock = connection.create_connection(
  File "D:\anaconda3\envs\SeisBench\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    raise err
  File "D:\anaconda3\envs\SeisBench\lib\site-packages\urllib3\util\connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

**Comment by yetinam** [comment] 2023-06-12 13:06
Duplicate of #206. Tracking the progress there. Thanks for reporting!

**Closed** 2023-06-12 13:06 UTC
